configuration: Release

version: 1.0.{build}

image: Visual Studio 2017

build:
    parallel: true
    publish_nuget: true
    verbosity: minimal

before_build:
  - dotnet restore
  
branches:
    only:
      - master

deploy:
  provider: NuGet
  api_key:
    secure: +eiMGysX5amlgkjLSzFdt0TwBOhnQrr+JCl/R38w2yg=
  skip_symbols: false
  artifact: /.*\.nupkg/
  
    

  
  


